local Length = require(script.Length)
local Time = require(script.Time)
local Mass = require(script.Mass)
local Velocity = require(script.Velocity)
local Temperature = require(script.Temperature)
local Energy = require(script.Energy)
local Pressure = require(script.Pressure)
local Power = require(script.Power)
local Volume = require(script.Volume)
local Density = require(script.Density)
local Area = require(script.Area)

--- @type Newton Float
--- @within Physics
export type Volt = number
export type Amp = number
export type Ohm = number
export type Newton = number
export type MetersPerSecondSquared = number
export type LightYear = Length.LightYear
export type LightMinute = Length.LightMinute
export type LightSecond = Length.LightSecond
export type AstronomicalUnit = Length.AstronomicalUnit
export type League = Length.League
export type Mile = Length.Mile
export type Kilometer = Length.Kilometer
export type Meter = Length.Meter
export type Feet = Length.Feet
export type Centimeter = Length.Centimeter
export type Millimeter = Length.Millimeter
export type Micrometer = Length.Micrometer
export type Nanometer = Length.Nanometer
export type Picometer = Length.Picometer
export type Planck = Length.Planck
export type Millenia = Time.Millenia
export type Century = Time.Century
export type Decade = Time.Decade
export type Year = Time.Year
export type Week = Time.Week
export type Day = Time.Day
export type Hour = Time.Hour
export type Minute = Time.Minute
export type Second = Time.Second
export type Millisecond = Time.Millisecond
export type Microsecond = Time.Microsecond
export type Nanosecond = Time.Nanosecond
export type Picosecond = Time.Picosecond
export type Ounce = Mass.Ounce
export type Pound = Mass.Pound
export type Stone = Mass.Stone 
export type Ton = Mass.Ton
export type Kiloton = Mass.Kiloton
export type Megaton = Mass.Megaton
export type Gram = Mass.Gram
export type Kilogram = Mass.Kilogram
export type Milligram = Mass.Milligram
export type Tonne = Mass.Tonne
export type Kilotonne = Mass.Kilotonne
export type Megatonne = Mass.Megatonne
export type MetersPerSecond = Velocity.MetersPerSecond
export type KilometersPerHour = Velocity.KilometersPerHour
export type Knot = Velocity.Knot
export type FeetPerSecond = Velocity.FeetPerSecond
export type MilesPerHour = Velocity.MilesPerHour
export type Fahrenheit = Temperature.Fahrenheit
export type Celsius = Temperature.Celsius
export type Kelvin = Temperature.Kelvin
export type Joule = Energy.Joule
export type Kilojoule = Energy.Kilojoule
export type Megajoule = Energy.Megajoule
export type Calorie = Energy.Calorie
export type Kilocalorie = Energy.Kilocalorie
export type BritishThermalUnit = Energy.BritishThermalUnit
export type Gigajoule = Energy.Gigajoule
export type Kilowatt = Power.Kilowatt
export type Watt = Power.Watt
export type Megawatt = Power.Megawatt
export type Gigawatt = Power.Gigawatt
export type Horsepower = Power.Horsepower
export type FootPoundsPerMinute = Power.FootPoundsPerMinute
export type Megapascal = Pressure.Megapascal
export type Kilopascal = Pressure.Kilopascal
export type Pascal = Pressure.Pascal
export type Atmosphere = Pressure.Atmosphere
export type Bar = Pressure.Bar
export type Millibar = Pressure.Millibar
export type PoundsPerSquareInch = Pressure.PoundsPerSquareInch
export type KilogramMetersPerSecond = Power.KilogramMetersPerSecond
export type Liter = Volume.Liter
export type Milliliter = Volume.Milliliter
export type Kiloliter = Volume.Kiloliter
export type Cup = Volume.Cup
export type Pint = Volume.Pint
export type Quart = Volume.Quart
export type Gallon = Volume.Gallon
export type CubicFeet = Volume.CubicFeet
export type CubicInch = Volume.CubicInch
export type CubicMeter = Volume.CubicMeter
export type GramPerCubicCentimeter = Density.GramPerCubicCentimeter
export type KilogramsPerCubicMeter = Density.KilogramsPerCubicMeter
export type GramPerMilliliter = Density.GramPerMilliliter
export type SquareMeter = Area.SquareMeter
export type SquareCentimeter = Area.SquareCentimeter
export type SquareMillimeter = Area.SquareMillimeter
export type SquareFeet = Area.SquareFeet
export type SquareInch = Area.SquareInch
export type SquareYard = Area.SquareYard
export type SquareKilometer = Area.SquareKilometer
export type SquareMile = Area.SquareMile
export type Acre = Area.Acre
export type Hectare = Area.Hectare

return {
	Length = Length,
	Time = Time,
	Mass = Mass,
	Velocity = Velocity,
	Temperature = Temperature,
	Energy = Energy,
	Pressure = Pressure,
	Power = Power,
}